[33mWARNING [0m selenium.webdriver.common.selenium_manager:selenium_manager.py:135 The chromedriver version (128.0.6613.137) detected in PATH at D:\Python\Scripts\chromedriver.exe might not be compatible with the detected chrome version (129.0.6668.90); currently, chromedriver 129.0.6668.100 is recommended for chrome 129.*, so it is advised to delete the driver in PATH and retry
[32mINFO    [0m Test_UserProfile:test_UserProfile.py:51 Testcase test_Signup_002 is started
[32mINFO    [0m Test_UserProfile:test_UserProfile.py:53 Opening browser
[32mINFO    [0m Test_UserProfile:test_UserProfile.py:56 UserCFqVOz
[32mINFO    [0m Test_UserProfile:test_UserProfile.py:58 Entering the Password
[32mINFO    [0m Test_UserProfile:test_UserProfile.py:60 UserXolbJj@gmail.com
[32mINFO    [0m Test_UserProfile:test_UserProfile.py:62 7453995758
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028408367CB0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/1a673ff5e455cfc607406e8229500c44
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028408A6C200>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/1a673ff5e455cfc607406e8229500c44
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028408A6CD40>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/1a673ff5e455cfc607406e8229500c44